version: '3.1'

volumes:

services:
  # Навание для сервиса, контейнер для которой будем поднимать
  postgres_database_service:
    # Образ, из которого будут создаваться контейнеры.
    # В данном случае берем официальный образ postgres
    image: postgres
    # Имя, которое будет присвоено контейнеру после его запуска.
    container_name: postgres_database_container
    # Режим перезапуска. Говорит, в каких случаях контейнер должен стартовать.
    restart: always
    # Для работы БД в контейнере пробрасывается каталог хостового компьютера.
    # После удаления контейнера данные останутся на компьютере.
    # В этом примере в каталоге /data будет создан каталог postgres_db, 
    # который будет прокинут в каталог /va/postgres_db/data контейнера
    volumes:
      - /data/postgres_db/:/var/lib/postgres_db/data
    # Для первого запуска необходима инициализация базы данных.
    # Без пароля системы выдает ошибку. Поэтому задаем переменную POSTGRES_PASSWORD
    environment:
      POSTGRES_PASSWORD: postgres_password
